# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a43427bc0279c9692d1887cff1d3cbe440aab52052a4145ba05b6e10ed23d524674d8e87c5d07080d1fcc1684b3fe968cb5088226eaf7afc58213baf1e854029

test:
  secret_key_base: 96fe4bea97fef6c9ea1772daae34abf1a0aded59e3df73eda759ac7ad18363e628b5f5afa43988d3d7c394233a9df7bb636ea36cd1f45eb888ac89a2bc66899f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
